stages:
  - test

default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://gitlab.lanl.gov

#variables:
#  GIT_STRATEGY: clone

test:
  stage: test
  variables:
    SCHEDULER_PARAMETERS: -p shared-gpu -q debug -t 1:00:00
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - darwin
    - batch
  timeout: 1h
  script:
    - module load cmake cuda/12.0.0
    - module list
    - cd ${CI_PROJECT_DIR}
    - cmake -B build -DKokkos_ENABLE_TESTS=OFF -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_OPENMP=ON
    - cmake --build build -j $(nproc)
    - ctest --test-dir build --output-on-failure