stages:
  - build_and_test

default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://gitlab.lanl.gov

variables:
  SPACK_DISABLE_LOCAL_CONFIG: "true"
  GIT_DEPTH: 1
  GIT_STRATEGY: clone

build_and_test:
  stage: build_and_test
  tags:
    - darwin
    - batch
  timeout: 1h
  variables:
    SCHEDULER_PARAMETERS: -p shared-gpu -q debug -t 1:00:00
  before_script:
    - module list
    - git clone https://github.com/kokkos/kokkos.git
    - cd kokkos
    - cmake -B build -DKokkos_ENABLE_TESTS=OFF -DKokkos_ENABLE_CUDA=ON -DCMAKE_CXX_EXTENSIONS=OFF
    - cmake --build build -j $(nproc)
    - cmake --install build --prefix "${CI_PROJECT_DIR}/kokkos/install" > /dev/null
  script:
    - cd ${CI_PROJECT_DIR}
    - cmake -B build -DKokkos_ROOT="${CI_PROJECT_DIR}/kokkos/install"
    - cmake --build build -j $(nproc)
    - ctest --test-dir build --output-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH