name: ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure with CMake
        run: |
          cmake -B "${{ github.workspace }}/build" \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DKokkos_ENABLE_TESTS=OFF \
                -DKokkos_ENABLE_CUDA=OFF \
                -DKokkos_ENABLE_OPENMP=ON

      - name: Build
        run: |
          cmake --build "${{ github.workspace }}/build" --parallel $(nproc)

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure